# -*- coding: utf-8 -*-
"""HPA_XML_Parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1foywmUmCK1zkRTXE_MHgK-rjTvRoqvoY
"""

#@title Aperte o 'play' aqui primeiro
import pandas as pd
from xml.etree import ElementTree
from xml.etree.ElementTree import Element
from xml.etree.ElementTree import SubElement
from itertools import chain

#@title Copie o caminho do arquivo e aperte o 'play'
pathin = input('Insira o caminho do arquivo aqui: ')
pathout = pathin.replace('xml', 'xlsx')
pathout = pathout.strip("''")

#@title nTPM das regiões do cérebro
def hpa_parser_all_all_fast(regionID, rt):
    
    bc = []

    for typedata in rt.iter('rnaExpression'):
        if typedata.attrib['assayType'] == "humanBrain":
            for data in typedata.iter('data'):
                for region in data.iter('tissue'):
                    if region.text == regionID:
                        for rna in data.findall('RNASample'):
                            ls = list(rna.attrib.values())
                            ls.append(region.text)
                            ls.append(region.attrib['organ'])
                            bc.append(ls)
    
    df = pd.DataFrame(bc)
    df = df.rename(columns={0: 'ID', 1: 'Variable', 2: 'nTPM', 3: 'Sex', 4: 'Age', 5: 'Region', 6: 'Organ'})
    return(df)

def loop_parser(path, file):
    
    datalist = []
    lst = []
    document = ElementTree.parse(path)
    rt = document.getroot()

    for typedata in rt.iter('rnaExpression'):
        if typedata.attrib['assayType'] == "humanBrain":
            for data in typedata.iter('data'):
                for region in data.iter('tissue'):
                    lst.append(region.text)
                    
    for word in lst:
        df = hpa_parser_all_all_fast(regionID= word, rt=rt)
        datalist.append(df) 
    df = pd.concat(datalist, ignore_index=True)
    with pd.ExcelWriter(file) as writer:
        df.to_excel(writer)

loop_parser(path= pathin, file= pathout)

#@title nTPM de todos os tecidos
def hpa_parser_all_all_fast(regionID, rt):
    
    bc = []

    for typedata in rt.iter('rnaExpression'):
        if typedata.attrib['assayType'] == "tissue":
            for data in typedata.iter('data'):
                for region in data.iter('tissue'):
                    if region.text == regionID:
                        for rna in data.findall('RNASample'):
                            ls = list(rna.attrib.values())
                            ls.append(region.text)
                            ls.append(region.attrib['organ'])
                            bc.append(ls)
    
    df = pd.DataFrame(bc)
    df = df.rename(columns={0: 'ID', 1: 'Variable', 2: 'nTPM', 3: 'Sex', 4: 'Age', 5: 'Region', 6: 'Organ'})
    return(df)

def loop_parser(path, file):
    
    datalist = []
    lst = []
    document = ElementTree.parse(path)
    rt = document.getroot()

    for typedata in rt.iter('rnaExpression'):
        if typedata.attrib['assayType'] == "tissue":
            for data in typedata.iter('data'):
                for region in data.iter('tissue'):
                    lst.append(region.text)
                    
    for word in lst:
        df = hpa_parser_all_all_fast(regionID= word, rt=rt)
        datalist.append(df) 
    df = pd.concat(datalist, ignore_index=True)
    with pd.ExcelWriter(file) as writer:
        df.to_excel(writer)

loop_parser(path= pathin, file= pathout)